### PR TITLE
fix some bugs from scrum board

### PR DESCRIPTION
**Pull request by pawel150199**
This PR should fix following bugs:
*  In the same time should be only one badge on „zgłoszenia” it doesnt have sense another way
* „Zaloguj się” should be also add in navbar
*  Zarejestruj drużynę show in navbar when someone is already log

### CODE REVIEW

**Comment by pawel150199** [comment]
[Zarejestruj drużynę show in navbar when someone is already log](https://trello.com/c/Br4y88Mc/56-zarejestruj-dru%C5%BCyn%C4%99-show-in-navbar-when-someone-is-already-log)

**Comment by pawel150199** [comment]
[„Zaloguj się” should be also add in navbar](https://trello.com/c/P3SM6vx8/58-zaloguj-si%C4%99-should-be-also-add-in-navbar)

**Comment by pawel150199** [comment]
[In the same time should be only one badge on „zgłoszenia” it doesnt have sense another way](https://trello.com/c/lXfk83KA/59-in-the-same-time-should-be-only-one-badge-on-zg%C5%82oszenia-it-doesnt-have-sense-another-way)

**Review by Kduszynska — APPROVED** [review]
+1

**Review by Kduszynska — APPROVED** [review]
+1

**Pull request merged**
